sudo: required
language: php
dist: trusty

php:
  - 7.1

services:
  - postgresql

before_install:
  - cp .env.travis .env

install:
  - travis_retry composer install --no-interaction

before_script:
  - psql -c 'create database elecom;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &

script:
  - php artisan migrate
  - php artisan dusk
