sudo: required
language: php
dist: trusty

php:
  - 7.1

env:
  - APP_ENV=testing
  - APP_KEY=base64:M6EqxhQS/snjZGujrI3yntQ2M62pCTrSz9dXzVDD0G0=
  - APP_DEBUG=true
  - APP_URL=http://127.0.0.1:8000
  - DB_DATABASE=elecom
  - DB_USERNAME=postgres

cache:
  directories:
  - $HOME/.composer/cache/files

services:
  - postgresql

before_install:
  - cp .env.travis .env

install:
  - travis_retry composer install --no-interaction

before_script:
  - psql -c 'create database elecom;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &
  - php artisan key:generate

script:
  - php artisan dusk
