sudo: required
language: php
dist: trusty

php:
  - 7.1

cache:
  directories:
  - $HOME/.composer/cache/files

before_install:
  - cp .env.travis .env

install:
  - travis_retry composer install --no-interaction

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &
  - php artisan key:generate

script:
  - php artisan dusk
